version: 2
updates:
- package-ecosystem: maven
  directory: "/geSuit-parent"
  schedule:
    interval: weekly
    day: friday
    time: "09:00"
    timezone: Australia/ACT
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: io.dropwizard.metrics:metrics-core
    versions:
    - 4.1.17
    - 4.1.18
  - dependency-name: com.zaxxer:HikariCP
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: org.bstats:bstats-bungeecord
    versions:
    - 2.1.0
